# Generated by Django 5.2.1 on 2025-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
