# Generated by Django 5.2.1 on 2025-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Fast', 'Fast'), ('Standard', 'Standard')], max_length=100),
        ),
    ]
